<a href="https://colab.research.google.com/github/Bigmanibrah/Bigmanibrah/blob/main/Copy_of_RTApredictions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
ibraah=pd.read_csv('/content/dft-road-casualty-statistics-casualty-provisional-mid-year-unvalidated-2023.csv')
print("shape od the dataset",ibraah.shape)
ibraah.head(20)

shape od the dataset (62674, 19)

,collision_index,collision_year,collision_reference,vehicle_reference,casualty_reference,casualty_class,sex_of_casualty,age_of_casualty,age_band_of_casualty,casualty_severity,pedestrian_location,pedestrian_movement,car_passenger,bus_or_coach_passenger,pedestrian_road_maintenance_worker,casualty_type,casualty_home_area_type,casualty_imd_decile,lsoa_of_casualty
0,2023010419171,2023,010419171,1,1,3,2,20,4,3,5,1,0,0,0,0,1,10,E01030370
1,2023010419183,2023,010419183,2,1,1,1,25,5,3,0,0,0,0,0,9,1,3,E01001546
2,2023010419183,2023,010419183,3,2,2,2,38,7,3,0,0,2,0,0,9,-1,-1,-1
3,2023010419189,2023,010419189,1,1,1,1,50,8,3,0,0,0,0,0,9,1,5,E01002443
4,2023010419191,2023,010419191,2,1,1,1,34,6,3,0,0,0,0,0,1,1,2,E01004679
5,2023010419192,2023,010419192,2,1,1,1,24,5,3,0,0,0,0,0,3,-1,-1,-1
6,2023010419198,2023,010419198,1,1,3,1,65,9,3,4,4,0,0,0,0,1,5,E01023593
7,2023010419201,2023,010419201,1,1,1,1,22,5,3,0,0,0,0,0,1,2,10,E01026413
8,2023010419205,2023,010419205,1,1,1,1,20,4,3,0,0,0,0,0,9,1,3,E01003629
9,2023010419209,2023,010419209,1,1,3,1,33,6,3,8,1,0,0,0,0,1,8,E01000989
10,2023010419223,2023,010419223,1,1,1,2,58,9,3,0,0,0,0,0,9,1,5,E01002619
11,2023010419228,2023,010419228,1,1,1,1,40,7,3,0,0,0,0,0,9,1,2,E01003265
12,2023010419228,2023,010419228,1,2,2,-1,-1,-1,3,0,0,1,0,0,9,-1,-1,-1
13,2023010419228,2023,010419228,1,3,2,-1,-1,-1,3,0,0,1,0,0,9,-1,-1,-1
14,2023010419245,2023,010419245,1,1,1,1,56,9,3,0,0,0,0,0,9,1,3,E01001794
15,2023010419259,2023,010419259,1,1,2,2,44,7,3,0,0,2,0,0,9,1,4,E01002719
16,2023010419259,2023,010419259,1,2,2,2,42,7,3,0,0,2,0,0,9,1,4,E01002719
17,2023010419259,2023,010419259,1,3,2,2,20,4,3,0,0,2,0,0,9,1,6,E01002024
18,2023010419261,2023,010419261,1,1,1,1,49,8,3,0,0,0,0,0,8,1,5,E01003638
19,2023010419263,2023,010419263,1,1,1,1,28,6,3,0,0,0,0,0,3,1,2,E01004435

In [ ]:
import pandas as pd
ibraah=pd.read_csv('/content/dft-road-casualty-statistics-casualty-provisional-mid-year-unvalidated-2023.csv')
data=ibraah.loc[:,('casualty_severity','age_of_casualty')]
data.head(20)

    casualty_severity  age_of_casualty
0                   3               20
1                   3               25
2                   3               38
3                   3               50
4                   3               34
5                   3               24
6                   3               65
7                   3               22
8                   3               20
9                   3               33
10                  3               58
11                  3               40
12                  3               -1
13                  3               -1
14                  3               56
15                  3               44
16                  3               42
17                  3               20
18                  3               49
19                  3               28